version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    username: sparkpost
    password: ${{secrets.NPM_PASSWORD}}
updates:
  - package-ecosystem: "npm"
    directory: “/“
    registries: 
      - npm-npmjs
    schedule:
      interval: daily
      time: "02:04"
      timezone: "America/New_York"
    allow:
      - dependency-type: "all"
    labels:
      - "dependabot"
      - "auto-request"
