name: "Dependabot Automerge"
on: 
  pull_request:
    types: opened
  schedule:
    - cron: '40 13 * * *'
  workflow_dispatch:
    inputs:
      combineBranchName:
          description: 'Name of the branch to merge'
          required: true
          default: 'combine-prs-branch'
jobs:
  automerge-prs:
    runs-on: ubuntu-latest
    steps:
    # get the names of the pull requests to merge
      - uses: actions/github-script@v3
        name: Auto Merge Dependabot Pull Requests
        env:
          COMBINE_BRANCH_NAME: 'combine-prs-branch'
        with:
          github-token: ${{secrets.DEPENDABOT_TOKEN}}
          script: |
            const pulls = await github.paginate('GET /repos/:owner/:repo/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            for (const pull of pulls) {
              const branchName = 
              if (github.actor == 'dependabot[bot]' || pull['head']['ref'] == $COMBINE_BRANCH_NAME) {
                github.pullRequests.createReview({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE'
              })
              github.pullRequests.merge({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number
              })
            }
            }
   
